image:
  name: hashicorp/terraform:1.5.7
  entrypoint: ["/usr/bin/env"]

variables:
  TF_IN_AUTOMATION: "true"
  TF_INPUT: "false"
  TF_ADDRESS: "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/terraform/state/${TF_STATE_NAME}"
  AWS_DEFAULT_REGION: ${AWS_REGION}
  
before_script:
  - terraform --version
  - aws --version
  - export AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
  - export AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
  - export AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION}

stages:
  - init
  - validate
  - plan
  - apply

cache:
  key: "terraform"
  paths:
    - ${CI_PROJECT_DIR}/.terraform

# Common job definitions
.terraform_init: &terraform_init
  before_script:
    - cd ${TF_ROOT}
    - terraform --version
    - terraform init -backend-config="address=${TF_ADDRESS}" -backend-config="lock_address=${TF_ADDRESS}/lock" -backend-config="unlock_address=${TF_ADDRESS}/lock" -backend-config="username=${CI_PROJECT_ID}" -backend-config="password=${CI_JOB_TOKEN}" -backend-config="lock_method=POST" -backend-config="unlock_method=DELETE" -backend-config="retry_wait_min=5" -reconfigure

# Environment-specific configurations
.terraform_job: &terraform_job
  script:
    - cd ${TF_ROOT}
    - terraform ${TF_COMMAND} ${TF_ARGS}
  artifacts:
    when: on_success
    paths:
      - ${TF_ROOT}/planfile
    expire_in: 1 week

# Staging environment jobs
init:staging:
  extends: .terraform_job
  stage: init
  variables:
    TF_ROOT: "environments/staging"
    TF_STATE_NAME: "staging"
    TF_COMMAND: "init"
    TF_ARGS: ""
  rules:
    - if: '$CI_COMMIT_BRANCH == "staging"'
      when: manual
      allow_failure: false

validate:staging:
  extends: .terraform_job
  stage: validate
  variables:
    TF_ROOT: "environments/staging"
    TF_COMMAND: "validate"
    TF_ARGS: ""
  needs: ["init:staging"]
  rules:
    - if: '$CI_COMMIT_BRANCH == "staging"'
      when: manual
      allow_failure: false

plan:staging:
  extends: .terraform_job
  stage: plan
  variables:
    TF_ROOT: "environments/staging"
    TF_COMMAND: "plan"
    TF_ARGS: "-out=planfile"
  needs: ["validate:staging"]
  rules:
    - if: '$CI_COMMIT_BRANCH == "staging"'
      when: manual
      allow_failure: false

apply:staging:
  extends: .terraform_job
  stage: apply
  variables:
    TF_ROOT: "environments/staging"
    TF_COMMAND: "apply"
    TF_ARGS: "-auto-approve planfile"
  needs: ["plan:staging"]
  environment:
    name: staging
    url: https://s3.console.aws.amazon.com/s3/buckets/
  rules:
    - if: '$CI_COMMIT_BRANCH == "staging"'
      when: manual
      allow_failure: false

# Production environment jobs
init:production:
  extends: .terraform_job
  stage: init
  variables:
    TF_ROOT: "environments/production"
    TF_STATE_NAME: "production"
    TF_COMMAND: "init"
    TF_ARGS: ""
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual
      allow_failure: false

validate:production:
  extends: .terraform_job
  stage: validate
  variables:
    TF_ROOT: "environments/production"
    TF_COMMAND: "validate"
    TF_ARGS: ""
  needs: ["init:production"]
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual
      allow_failure: false

plan:production:
  extends: .terraform_job
  stage: plan
  variables:
    TF_ROOT: "environments/production"
    TF_COMMAND: "plan"
    TF_ARGS: "-out=planfile"
  needs: ["validate:production"]
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual
      allow_failure: false

apply:production:
  extends: .terraform_job
  stage: apply
  variables:
    TF_ROOT: "environments/production"
    TF_COMMAND: "apply"
    TF_ARGS: "-auto-approve planfile"
  needs: ["plan:production"]
  environment:
    name: production
    url: https://s3.console.aws.amazon.com/s3/buckets/
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      when: manual
      allow_failure: false
